// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/news/news_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/mfsyahrz/bareksaproject/internal/domain/entity"
	constant "github.com/mfsyahrz/bareksaproject/internal/shared/constant"
)

// MockNewsService is a mock of NewsService interface.
type MockNewsService struct {
	ctrl     *gomock.Controller
	recorder *MockNewsServiceMockRecorder
}

// MockNewsServiceMockRecorder is the mock recorder for MockNewsService.
type MockNewsServiceMockRecorder struct {
	mock *MockNewsService
}

// NewMockNewsService creates a new mock instance.
func NewMockNewsService(ctrl *gomock.Controller) *MockNewsService {
	mock := &MockNewsService{ctrl: ctrl}
	mock.recorder = &MockNewsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsService) EXPECT() *MockNewsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNewsService) Create(ctx context.Context, news entity.News) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, news)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNewsServiceMockRecorder) Create(ctx, news interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNewsService)(nil).Create), ctx, news)
}

// DeleteByID mocks base method.
func (m *MockNewsService) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockNewsServiceMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockNewsService)(nil).DeleteByID), ctx, id)
}

// FindAll mocks base method.
func (m *MockNewsService) FindAll(ctx context.Context, status constant.NewsStatus, topicID int64) ([]entity.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, status, topicID)
	ret0, _ := ret[0].([]entity.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockNewsServiceMockRecorder) FindAll(ctx, status, topicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockNewsService)(nil).FindAll), ctx, status, topicID)
}

// FindOne mocks base method.
func (m *MockNewsService) FindOne(ctx context.Context, id int64) (*entity.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*entity.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockNewsServiceMockRecorder) FindOne(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockNewsService)(nil).FindOne), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockNewsService) UpdateByID(ctx context.Context, news entity.News) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, news)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockNewsServiceMockRecorder) UpdateByID(ctx, news interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockNewsService)(nil).UpdateByID), ctx, news)
}
